# generated by datamodel-codegen:
#   filename:  payload.json
#   timestamp: 2025-01-13T02:50:07+00:00

from __future__ import annotations

from pydantic import BaseModel


class RequestInput(BaseModel):
    prompt: str
