/*
 * @Author: mulingyuer
 * @Date: 2024-11-20 14:55:39
 * @LastEditTime: 2024-11-20 14:59:30
 * @LastEditors: mulingyuer
 * @Description: 语言数据
 * @FilePath: \chrome-extension\src\pages\side-panel\views\whisper\language.ts
 * 怎么可能会有bug！！！
 */

export const Languages = [
	{ name: "简体中文", value: "zh-CN" },
	{ name: "繁体中文", value: "zh-TW" },
	{ name: "粤语", value: "yue" },
	{ name: "英语", value: "en" },
	{ name: "南非荷兰语", value: "af" },
	{ name: "阿姆哈拉语", value: "am" },
	{ name: "阿拉伯语", value: "ar" },
	{ name: "阿萨姆语", value: "as" },
	{ name: "阿塞拜疆语", value: "az" },
	{ name: "巴什基尔语", value: "ba" },
	{ name: "白俄罗斯语", value: "be" },
	{ name: "保加利亚语", value: "bg" },
	{ name: "孟加拉语", value: "bn" },
	{ name: "藏语", value: "bo" },
	{ name: "布列塔尼语", value: "br" },
	{ name: "波斯尼亚语", value: "bs" },
	{ name: "加泰罗尼亚语", value: "ca" },
	{ name: "捷克语", value: "cs" },
	{ name: "威尔士语", value: "cy" },
	{ name: "丹麦语", value: "da" },
	{ name: "德语", value: "de" },
	{ name: "希腊语", value: "el" },
	{ name: "西班牙语", value: "es" },
	{ name: "爱沙尼亚语", value: "et" },
	{ name: "巴斯克语", value: "eu" },
	{ name: "波斯语", value: "fa" },
	{ name: "芬兰语", value: "fi" },
	{ name: "法罗语", value: "fo" },
	{ name: "法语", value: "fr" },
	{ name: "加利西亚语", value: "gl" },
	{ name: "古吉拉特语", value: "gu" },
	{ name: "豪萨语", value: "ha" },
	{ name: "夏威夷语", value: "haw" },
	{ name: "希伯来语", value: "he" },
	{ name: "印地语", value: "hi" },
	{ name: "克罗地亚语", value: "hr" },
	{ name: "海地克里奥尔语", value: "ht" },
	{ name: "匈牙利语", value: "hu" },
	{ name: "亚美尼亚语", value: "hy" },
	{ name: "印尼语", value: "id" },
	{ name: "冰岛语", value: "is" },
	{ name: "意大利语", value: "it" },
	{ name: "日语", value: "ja" },
	{ name: "爪哇语", value: "jw" },
	{ name: "格鲁吉亚语", value: "ka" },
	{ name: "哈萨克语", value: "kk" },
	{ name: "高棉语", value: "km" },
	{ name: "卡纳达语", value: "kn" },
	{ name: "韩语", value: "ko" },
	{ name: "拉丁语", value: "la" },
	{ name: "卢森堡语", value: "lb" },
	{ name: "林加拉语", value: "ln" },
	{ name: "老挝语", value: "lo" },
	{ name: "立陶宛语", value: "lt" },
	{ name: "拉脱维亚语", value: "lv" },
	{ name: "马尔加什语", value: "mg" },
	{ name: "毛利语", value: "mi" },
	{ name: "马其顿语", value: "mk" },
	{ name: "马拉雅拉姆语", value: "ml" },
	{ name: "蒙古语", value: "mn" },
	{ name: "马拉地语", value: "mr" },
	{ name: "马来语", value: "ms" },
	{ name: "马耳他语", value: "mt" },
	{ name: "缅甸语", value: "my" },
	{ name: "尼泊尔语", value: "ne" },
	{ name: "荷兰语", value: "nl" },
	{ name: "挪威尼恩斯克语", value: "nn" },
	{ name: "挪威语", value: "no" },
	{ name: "奥克语", value: "oc" },
	{ name: "旁遮普语", value: "pa" },
	{ name: "波兰语", value: "pl" },
	{ name: "普什图语", value: "ps" },
	{ name: "葡萄牙语", value: "pt" },
	{ name: "罗马尼亚语", value: "ro" },
	{ name: "俄语", value: "ru" },
	{ name: "梵语", value: "sa" },
	{ name: "信德语", value: "sd" },
	{ name: "僧伽罗语", value: "si" },
	{ name: "斯洛伐克语", value: "sk" },
	{ name: "斯洛文尼亚语", value: "sl" },
	{ name: "绍纳语", value: "sn" },
	{ name: "索马里语", value: "so" },
	{ name: "阿尔巴尼亚语", value: "sq" },
	{ name: "塞尔维亚语", value: "sr" },
	{ name: "巽他语", value: "su" },
	{ name: "瑞典语", value: "sv" },
	{ name: "斯瓦希里语", value: "sw" },
	{ name: "泰米尔语", value: "ta" },
	{ name: "泰卢固语", value: "te" },
	{ name: "塔吉克语", value: "tg" },
	{ name: "泰语", value: "th" },
	{ name: "土库曼语", value: "tk" },
	{ name: "菲律宾语", value: "tl" },
	{ name: "土耳其语", value: "tr" },
	{ name: "鞑靼语", value: "tt" },
	{ name: "乌克兰语", value: "uk" },
	{ name: "乌尔都语", value: "ur" },
	{ name: "乌兹别克语", value: "uz" },
	{ name: "越南语", value: "vi" },
	{ name: "意第绪语", value: "yi" },
	{ name: "约鲁巴语", value: "yo" }
];
